# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpagerank',
            name='lastScanData',
            field=models.DateField(auto_now_add=True),
        ),
    ]
